### ISSUE TITLE
Move IO\ , Filesystem\ etc out of experimental

### ISSUE THREAD

**Issue by fredemmott** [hhvm/hsl-experimental#21]
- [x] Make `\stream_await()` indicate failure for non-awaitable fds (FB: D10341063)
- [x] add support for per-operation timeouts. These will stack. eg `writeAsync('foo', 1000); await writeAsync('bar', 1000);` - the second await woudl naively take up to ~ 2000 ms
- [x] add socket support
- [x] ~add thread-pooled sockets~ request-pooled, which can be done by users; thread-pooled unsafe except for fixed-length messages that are small enough to be atomic
- [x] add true native async socket connections
- [x] add async equivalent of stream_socket_accept()
- [x] add ReadWrite modes
- [x] add more-specific exceptions (#37)
- [x] move UnixSocket\ to Unix\
- [x] move basic errno-based-exception stuff to trait
- [x] split seekable to a new interface (#68 and #71)
- [x] new native interfaces (#77)
- [x] support CLI server (likely dupe of 'new native interfaces'); error handling is based on `errno`, which is not handled correctly by CLI client/server, and it is unclear what behavior would be correct.
- [x] documentation
- [x] ~move Unix\ to Local\ (AF_UNIX is a deprecated alias of AF_LOCAL)~ un-deprecated, AF_LOCAL not in recent POSIX standards
- [x] solve or accept interface explosion:
  - denotable intersection types would reduce from (n+2^n) interfaces to (n). Unclear if will be a hack feature
  - is the current interface approach actually usable?
    - test by leaving as-is until 2020
  - the current approach is not scalable. Does this matter?
    - do we get more interfaces after Seekable? is `n` actually going to get bigger?
  - if not solveable or acceptable, redesign to remove the bulk of the interfaces. In most languages/libraries:
    - allow all operations on all handles and raise exceptions or otherwise report errors
    - specialized abstractions (e.g. C++ istream, ostream) are provided for "I don't do anything except write to this" and "I don't do anything except read from this" - no metadata, seek etc. Java goes a little bit further (e.g. `RandomAccessFile`), but not as throughly as the current HSL IO

**Comment by fredemmott** [comment]
>  add async equivalent of stream_socket_accept()

An alternative would be a true TCP server mode - each request gets the socket, but no HTTP-request-related content.

Doing both would probably be best.

**Comment by azjezz** [comment]
> add socket support
> add true native async socket connections
> add async equivalent of stream_socket_accept()

those are being worked on here : #36

**Comment by azjezz** [comment]
> add ReadWrite modes
see #38

**Comment by fredemmott** [comment]
>  add support for per-operation timeouts. These will stack. eg writeAsync('foo', 1000); await writeAsync('bar', 1000); - the second await woudl naively take up to ~ 2000 ms

Should this be a per-handle write timeout and read-timeout, or actual per-operation timeout? The former makes more sense for sockets at least, as it's natively supported.

**Comment by azjezz** [comment]
+1 for timeout per-operation. 

also, maybe add #68, and #71 to the list :)

**Comment by fredemmott** [comment]
added "Move Unix\ to Local\" as AF_UNIX is a deprecated alias of AF_LOCAL in POSIX 1.g (2000)

**Comment by fredemmott** [comment]
Actual remaining blocker is getting wide agreement that a Disposable-based API would not be workable. Promising, I'm expecting to start work on making this built in in March.
